version: '3.7'

services:
  web_dev:
    restart: always
    build: ./Bodega
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Bodega/:/usr/src/Bodega
    ports:
      - 52000:8000
    env_file:
      - ./.env.dev
    links:
      - db:db
    depends_on:
      - db
  
  db:
    restart: always
    image: postgres:12.0-alpine
    # network_mode: host
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgres/data
    env_file:
      - ./.env.dev.db
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.dev.pg
    ports:
      - "53000:80"
    links:
      - db:db
    depends_on:
      - db

volumes:
  postgres_data:

