version: '3.7'

services:
  web:
    restart: always
    build: 
      context: ./Bodega
      dockerfile: Dockerfile.prod
    command: gunicorn Bodega.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db_prod
  
  db_prod:
    restart: always
    image: postgres:12.0-alpine
    # network_mode: host
    volumes:
      - ./postgres_data_prod:/var/lib/postgres/data
    env_file:
      - ./.env.prod.db
  
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data_prod:

