version: "3.8"

services:

  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - users_api
    networks:
      - prod_env_network

  users_api:
    # container_name: users_api
    build:
      context: ./APIS
      dockerfile: Dockerfile.prod
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    expose:
      - "3000-3010:3000"
    depends_on:
      - db
    networks:
      - prod_env_network
  
  db:
    image: postgres
    container_name: users_db
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    # ports:
    #   - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./users_prod_pgdata:/var/lib/postgresql/data
    networks:
      - prod_env_network

networks:
  prod_env_network:
    driver: bridge